server:
  port: 0
spring:
  application:
    name: incoming-material-service
  datasource:
    url: jdbc:h2:mem:nuthatch_db
    username: user
    password: secretPassword
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://kc.letsdigit.ru/realms/nuthatch/protocol/openid-connect/certs"
          issuer-uri: "https://kc.letsdigit.ru/realms/nuthatch"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

journal:
  service:
    document-service-uri: "http://document-service/api/v1/document"
    organization-service-uri: "http://organization-service/api/v1"