server:
  port: 8085
spring:
  application:
    name: incoming-material-service
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/nuthatch_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "https://kc.letsdigit.ru/realms/nuthatch/protocol/openid-connect/certs"
          issuer-uri: "https://kc.letsdigit.ru/realms/nuthatch"

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 10.16.0.10
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

journal:
  service:
    document-service-uri: "http://document-service/api/v1/document"
    organization-service-uri: "http://organization-service/api/v1"

