server:
  port: 8085
spring:
  application:
    name: address-service
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/nuthatch_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

# Discovery service client
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 10.16.0.8
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

# DaData env
dadata:
  client:
    base-url: "https://cleaner.dadata.ru/api/v1/clean/address"
    token: "token"
    secret-key: "secret-key"

# OpenAPI
springdoc:
  api-docs:
    path: /api-docs