server:
  port: 0
spring:
  application:
    name: address-service
  datasource:
    url: jdbc:h2:mem:nuthatch_db
    username: user
    password: secretPassword
    driver-class-name: org.h2.Driver
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
