server:
  port: 0
spring:
  application:
    name: address-service
  datasource:
    url: jdbc:h2:mem:nuthatch_db
    username: user
    password: secretPassword
    driver-class-name: org.h2.Driver
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
dadata:
  client:
    base-url: "https://cleaner.dadata.ru/api/v1/clean/address"
    token: "f1f221b267fd3d3766f57a61df24b9b0e8840131"
    secret-key: "c2c5e6470bfb318ba0b40ad33777effee2f6abd6"
