server:
  port: 0
spring:
  application:
    name: organization-service
  datasource:
    url: jdbc:h2:mem:nuthatch_db
    username: user
    password: secretPassword
    driver-class-name: org.h2.Driver
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

address:
  service:
    uri: "http://address-service/api/v1/address"
