server:
  port: 0
spring:
  application:
    name: organization-service
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/nuthatch_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}


organization:
  service:
    address-service-uri: "http://address-service/api/v1/address"
    document-service-uri: "http://document-service/api/v1/document"
