server:
  port: 8085
spring:
  application:
    name: building-service
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/nuthatch_db
    username: nuthatch-user
    password: secretPassword
    driver-class-name: org.postgresql.Driver

# Discovery service client
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}