server:
  port: 0

spring:
  application:
    name: document-service
  datasource:
    url: jdbc:h2:mem:nuthatch_db
    username: user
    password: secretPassword
    driver-class-name: org.h2.Driver

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

document:
  service:
    aws-access-key-id: ""
    aws-secret-access-key: ""
    aws-region: "ru-central1"
    aws-uri: "https://storage.yandexcloud.net"
    aws-bucket: "bcomms-01"
